export const data = `hDsDDttbhsmshNNWMNWGbTNqZq
VQfjnlFvnQFRdZWdVtqMGdWW
zvvvRnFFfjjlRBlBPzgQgRvvmtrmhHcptLHCDhcHHmLsBmsB
FrzFvvdTDcTnmTzdDTTzdvWmjhgVPrhSljSQSPwPjPjPjSVC
sMsGbqGsbbRqRbBMBGRMbLpNSSpjhlQljHVClhjgPjjPhlVp
sNbGtJbMfssNtvcnWFVmnvDd
TNfmdFJmfdZMQffVRQVV
jVHBCcDSjWrMZjvg
SShSbCGpcBtBtwtVLJJddmtLmT
CtpNftbNWbtSJDHqGZJFLfLr
dPsHlsRBHcZdqDFDZwwJ
snjVlvTPlPjVlQlHWjpSmzgNNzSmtpSm
qhZtSVqCqThGcGzZnnfZcB
WbddWbDwrBzcpzHpBb
DBBMFWRJDrDFWLWljCqjQjFvtCsqTjqs
vhFTzRzzTmPvbplWFtQttQQZtZhMZqcqSQ
fJVCfDfJNCLDwJNGmssZgwqgZcmtgcms
VmdVNLHGGVDBdfLCHnLGHnbWpTplWbddRTlzplWPpbFp
smwtNVqRjNmZjZBDSvzSzl
FnTJFcTTFccCrJGTLncdCCcPJZfBBDSlSJwZDlggSffvgSSf
FWTFGLFWLCPWrCnFnQWNbQVVwphhmHHbptVsss
BrrgrtgfBpPFhhgMWq
ZGvsvDGClvsSRScpGBhPphWMPhhTNh
SBSBdBZCcdwHrVQwQr
qmFqdVtqsVdzqGbwMJwGPpmPHM
ZjTjLQLLDrrLjcFhlfrGHppfbJwGpMMpGHwRCC
BTlZjrBBBcLTcDrjBlThWBjBtWNqnSzSnsSdvsFggNnqVVnv
zVvmjGgpcJnbTTTJHRHSRb
NPFrFQfCLPrdRlbtQRRvBtHb
frMLqPFMrfrPLCwqqNvjczwwnmwggGmssnmnnm
HbFJhhshsffcvslmGmLFrQBrlFTG
jNRPwwPjSPCdCdvRzRBTlRzmGrmB
nCSWdNjCCPqvtttZnDscth
ScSrRTPcSSDRWSptWcdmmWGbmGGLmLJvNJNbbJ
flzHjFpZjFfjjgszjlqzJNnnvsmbMmGvJLNNbmJv
jFZFVpffpVlqfQhgtTwcTVtrTcRBwBTD
rHrdGSMSSbZbjShj
qZfDBBvllvvWLtqbbQwhJjbtwbnQgN
WzWlzZmLWBLZLzCzrHMVcRrMRFRCCccF
BzdplppDlBBrqWnjFMBWqNWq
whZhZSSHhhVSrvSgHPvgvjnFTPsFFnnNTcjTFnTTsc
HLCwVSfZLffSHhLvwtQbJbrdGlRRrGdmpztG
grDFfDlfCftCzCfNztclNFrBNQjbZjJjjPPVsjNvsbvPsj
HwwTpGpRwMdpHWhvjzVsPJjJGVvVZs
ShphRpwzMWdpHdwWHwMpnHwLDmmgcLCCDtLDCCSlcgcfCD
ccqqLLqCqTSlZMLQMllZTvnNfjddttmmDpRJjvhfpfthRmdf
rbVssWwggFrGsWzPbVFGJpftQRPDmQDpdPmdJmfR
bBHWWHzWHWWHrsVbsFgwbFqqMLTnBclTMMSnLnqLqMQZ
CcSPGCCPrdPtdjcsBLDghbVLhqDl
vMJwTHzPvzVwqBBDblls
QNvMFfRMJHPZHjnfWmdftSjSnp
dnBCPhhBCrQfChdbNVGLszzDzVDsTbWT
HgcJgpppPqqHwPwJSczVzDssNNVWTtqVVGts
JHRFpjFccplcRwPJpHPScpMPQmCdBQQfQjjhCfBCrQQvdmnn
rQGmVRLRbDRHmmZLGBGVLHBVFspSstWWWNJcsgpQTSsNppJS
qlldhPdfCgnspJFWCFsFNT
jMMzwndfhnwPfqPMjgjMVBrGBmrHDHLZbjRGHbHj
wzpZfzHRSRfzgHfffZwwStCtSrBhBBCTrtFhhBFG
QPjQQQDcDWJNFWtrtWrGmTCMtmBW
lDvvDQcdjQcQLvlDwnpFgbbznZZglZsl
RfMFTMFrVrSRFPlFSfVlHpLqgzpHBLzHBBVzVpHG
CchbhcwdmdJmwJJtGgnqzppLmGGBQqQp
hCsstCJwLvMRvsZsTR
fQlfMlNClQhhZhrlWrWw
njDbnTDTBtGjmrGvSh
bgshBdBcDbTTdnnnTqcqLgqfpfQppCsCMsHHVVpHHNCHFF
PbCnTbzJnqQNzbbTNDdpwcmjDmwjGQjccw
hWgvSdLvwcGjSpSm
vVfrFvvhHFTZndJq
FFvRVCRqVRcfsDLrgqGNWjjHfhQQzGWjQHzN
ppJPBwplwSBJTmPpTzWWStzHHjNNLNzHNh
wnwMPbLJMJllJJwBmJmnLVvCvsCsbFgDrRrsCsvrqc
jqHgVgdgGQttWCtNqNflmllgFnfDnmFFlpcl
TZZsrrwwhwrsrZRGmhcfSnhGlmSFcf
rsLvvbJPPLBGPCQqHWtMCMHN
WzzBpCBpMsBpCvCfsgnPPfHgbfFNfF
jtdTLLjGTGjDjLbbbGlDLLLmfFgmmfgrPrgmNPHSnnNnqFSq
jbRRbjlwlRVpvWwvzBpB
qpwzCzCznFznTcCvrcrvVcLb
cPmNMHSlMsLfvWgsrWvL
mMHGPDMBGSGPHlPBcBPzznnzpdQFBjqRFdwdnn
QGZLJzmJrZgZzZhNQFqDWlWPWDFCWNRlPW
hMMbhVbhHWCsPWCMRs
BwjbSHVBVvfcTfZgZzQhrzdGrt
cvPTjfDPpDmmBjbQjZMdlBZj
CHNnghNChVzNgrFVwCMJLMMMMMQQdbLZ
FNSzShrHhNnWgVnWfvfbpfpDGTfvsG
FFpVrZhpTlSQlQzTtRtZHfmPmJDbRtZJ
jNnwBLnWwBgNBNCwsNgsMsCLVfDWfmDJRffmRRtmfRmPDRtR
BnLdNdjnBNcLngdCVBndgllFlQrrpQlSSFrQphFcQq
JmVLJPMNjmVJpMLJSVmNQZZQZZrnTHqZQHTrTTMr
ltfdwChhwRdRswDDdnBQqqWNTqrrHrqZRr
dwdwwDwsGlhhDFtsCwhsJLcPmGPcGzSjSjjLzNPS
QgSbgQCLQSJFMccLFLVVzH
WBNffrBpBNdNRdWDfptBtdzWcMZZVPMVwHMmsVHFccHsDsVc
ptphRWrfGRGRnqlCSQvhqbCzJS
VvdMLMLMBMlVlVschsNpDGpdNsGc
tqFSmnmnnttGfDqNcfvNDD
nzRHnrwrrWRrrzHtbMlTMBjCvWLgBBMl
pCBlRvzwzlCzvZqqDwzmvgtsLsQdgZsgPNtdrsWrst
JbGjbGVGHSFbhbnhTShSTbQtQrPsLsHLQgNRtsgdQsLP
GnnbJbGMGbSjjbSbCzqlwMRRDzqzMBBv
TTVRJVMWMshSQtjSVTQJRQlcCBncJccdppnJcBBDngFpgP
frvfzfHrwzZNrtNwzzzZncCCZFdFFCgBDpPcBcBg
LwNGbqwvmvvtbNQjQlVVRWTGTQWM
RnggwVLRLDfCVZhfpDGGMGMGcGzGNHvv
jmmWBTSsBmFmSzctsqpccHvzpN
SBSrTblSQPbQhNwwZfPVdZPf
CCvCwzfNStLzfrbmMJbZMtlsbJMW
gPPPBqDjBcPFpVgBRbnMsVsbJZnWsdbSbM
qgDPHjHcPhpDRRpPBRpCGSLwvHQwGfzrHLGLTL
CLGqDZZLTdddPsdJpq
gbRbbnghnrWvgrdJdSTRSsVNJlld
hMnwrjnnjggvnLDwGffTfwCZZZ
NzJHbNHNNzJzgmHmzpQSvvLqbLsVVsVGvB
WtWhtWDdrZldDWrWTlZgppVVsqQTVQBqsGqBsQVp
jWjWRRRlPcHRwJgw
CCnnFTmnPCMCRNfnwGwdfzvwwl
VQQVShDSSshhDDtDLhjccGjLBBzBzlZflNZvwZzdwBzpSNNZ
QLHhJDDhDhgscgtjbGHTrWbrTbRmbFrm
CJbLvJvbwtFHqvLzwJqqqtHWTWRgDScDRSWQQjTRcWRDLT
mssGsMNphZMNsPPBnhSjRgdnQRdWgdjgrcDn
GGmBMMsffmslMGshZlMphGqCzHCbzlbvzqwzzgFJggCF
WCgWBphpWLQZQpgdhGdwmfbfFRVRjRTbbSFttdbSbT
qqrZnDNqZJDTVzRjVFbfSN
rPMvqJJqrJMPJnZMZZgLPgLWLggWQghwhmBh
CWGGzdHHmPPSmPsC
LqwlZwRLrPMQlMqrlbZrQRsSNsmssSNSsNcBNpgmsJ
lwLDQhrDMQqPGfhzGGjhGn
ZqDlZssCqJJMvpdBpBBmBQSMRp
wLgVcbgFLzTLTNNZmNNRdjdRmF
HZHbctWTwgVWgsfrnnPqlnsWlD
RSnwSPFcLnFPnRwjzctzbGNlZgNbbGdGpLhZdpgM
BqqBfMvTmmJqDgGNVdGVbVJJZG
vsTDfqBmHmMWQCwjtrHjjSFFnRSn
LsCmmcDHRjdtNMstwwzJ
TvThqfBFBNTnnndTtL
lvGQfbFQGblFrRccLRSSlPPVHS
qbLpqTHSqpbqbrPcQgjPDjcdDL
gnzhhBBwBWZzMglmjDrDPjvfdvQPdwtd
WZZzZZlZmhsMmFgRBBBzHHJpNJGVRSJVGTVpNqCH
JDphhGhDdGzWRBnvqqLDNLMnLw
gsrTHHffTHPcrPrlHCNZhvBZnZNLhPvBNwvh
sHVCSsSghJpSJjQh
JTMGlfjlTdqjnqbnqFwqmnbQ
PBZhBBcWRZprPZcZDDCZTZRgnnzwbbsbnvhbvznFsNFFvvNQ
BcWrVgCCZTDRDrlGttfVtMddSJlH
vwwvpVbSvnSRRmfMCmTHVHTBHB
QLZgDPgSDgGTMZfmTTBZ
QDDsQFDlzlgtJlLdFDgSJQFvvpRvjqzjRwwwzWvhvWwqjj
mRRTGGNNflGRGGmmgRblsGwCZwVZlZjVwjztpjZhpBCB
PMLLFLHPLPnLqDDLvFDrzzMjhwVCjtphBzjMhV
FDdSPSpLcDsNRRWSTNWN
STldJthdJbtTqljCRDDHmqmj
VVvNwwvNFssJFJPNNwVvRMCgCgDqjjjqrDqqMHqP
QBZwQfZwfVhtcSBtBJnT
TzjjPzsQTslNlNzPRVGJJJGGtTJmgJHtmTZC
dBDWScMBhhPGgdwwJPfw
SqSqbSPDBhqnMqvrrSWVNFpRVRLzVQslvpNjVL
bWFgFCPFtgvDZWgtChDNFJHvGVzHHpjzHnnzGzzHRR
qcScQbbmqdQmlQmrlcQwLmHlRRjzGHnHJnnGVjHzBHzG
TqQwmLmfcddfwrfCgbWCNPsZNfCb
pddprrtrCPdvJdMjwwwHnLwwjLWCLg
qhzZTmZcmRhmpFlVHcQQVwWQHVQwnH
lGmhfRfmBZRlmmbvDPBMvNbvJJpP
NsptgfGLLNwnNQSZbCvZnRnMCb
JldhdzwzBMCSZvrz
JFcdWTdwhPTFVDVmTJNqmstLqgLtLtjGGpsG
dVVTSgTDpHVDjgdWpdpHTZSbWGrnnvrNwzFGNrFwnNNwvh
CPRlMPJcMQcBcsmmLCMPrzbFfhwfrvLrNNwwGwfF
CRJmtbmJlQbsQlRBpZDVjTHTdjDtSjZt
rQVJrRFdrwDfzHQHQBTnpWTW
PCLbPcPCsgqCgPgLjScSqNbHTzMtWmWtzlTHmBtTlMssMT
cCqghSSPcvgScPbwFGdDDVZFfDhZGB
zrRQRdqzPHQtnMPrtzPMRRQMVBBblJJBSClBpJbpdCCbBlCC
hTcGwzswGwGmGfDvvfGmGNfBpllVSWbWppNCBNBVpCBClW
gvGFTmTgwDhTDccsTfzfmfGGQPgPPqrgRZPHnRqRZrQLnRgP
hvmmJllPbmCRMNGMMlNwNl
PFTpTVjTgpTpBRgMGMnRNHBB
WWrqzTTPVQDPqpjTqPJbmLtcfsQsftbLbvct
SzrmpjjcsjTZNzgnnNzN
BLHNDwBLBPLwLBhwDVLgdQCgCQGTngHQZCngZd
PPJBDvBVVBmppNjJjrrr
ZHBNQFhsqHBsgCfqtctcPvSwPqrV
LlnGTnJpJJTmdDpmLlmLndWfVrPvvRwDfcwwwRVwcfQtvP
GnbQblWmWGdTJQdTGnZHsHhZhFNsbCsjFgjC
hWfDzDTVndDMhddMlBWMBDfJRnRtvvSSQjCvZCtjtpJvSR
bGHsccFcbscsqGPHNGcrpjJZtvSRtFtQCZrjSj
GsbwGGwNNGLgPLwMzBzfMMVMTLdTCC
GBcNzTSSmGzmTLNgvwgpNCDqpDggpw
JRZMrJWFZZnZtJgvvjwbpbCJDd
rFMPRhZtZFnWrRtQGmPPDcLfmGLTfz
VdWnVdjhhdFjVWbndMlNLQspVMHCNVlClV
RSrJBRRJwJSBQpMBHLLDCL
TqwtRRRJzJTSqJSzSrtmqgWWhcncvPgnWbPQnbnWmb
VnDFpPpFssVSpFDVHbRbscCvgbMTvTCR
JfzqdQBfhBdddfBBGDLdGQvbrqMMcCRRMTgbqgMrbbqc
QDfzJNWBJLQBhmdGDzDGhQGGlFZwPtWjtFFppllSVpZZFnjj
qrLLNpJbJnRLNnpvQtRVhhRFCdlFFlFd
mmjzjvGjwPwmTsSTSQjDVlVWQjlCDthCCC
cSSmcTTPcSswScfSHmTSTzJqqNrnpBpqBbJLvZMrqfrL
NSvRZRfFvfHSZQcNJBLbzDLnrDFnhtFLFnrh
wmTGpmGCwsMplMsHllPlMnDLjznrgrzDjgnntznr
dsCVGGGwmpTGPplmCmPppVmHSSRJNfJvBNZQfWdBRJZRBZcR
TwQwqDPQtwNwzNDTZcnZbJvMnMMbFqZM
SzGSjrjLWrjHHspWVhvVVnFJbccVZcRJbllb
pHppszGSprhhWHLCLrsjdTtDDPfwdfwtdNfDgNCN
ftcvBtBFtmBlmvPFmmcczCChrgSCzzCSnCSSnGHf
sJddbdTDbDHdnJRggrGzGzrG
dppDVDZMMMsTTVsDTsTDpwVctNcvBZQPcPctqtQcHmvlvQ
jzbdzztbDqNqwvLvRmQZjvRH
FSJbFFWgJnZFLRZmHmRQ
TgVJTVSJGJcJlllgTMdqpdNsrztNNsNbMDDp
CCCVWbwVnlRbTcqSShqGhhGcnF
PgDBfDpMNlfgpPfNZZtcJgcqqhmmjqSmjFmhmS
tpfpsPrlpsPDDMDfBZrwLrVWLLLWRCdHLTwbVR
pjvfDGjSMpvDmDpDpSDnJmfqbPVsCMFsPqFVPqCrwrbMFV
NQlHtHNhZHgZZNBHhQgzPmCwbqqVFlsrPFrFCP
hgHtQdQchcHctHgcgNgBQdWNpmvTWvpGmLJDLGjTpLGnnjfv
QhgLLLmtlRqDtRGP
HLbnCZFWVHLZnFCJJRFrGJzDGDGJDD
WZHfndfMfCZbMnTVTfZhSNQQpdwSdLwhNcmdSN
sPwrPMgLFPFFsLZtmcclSSZDtcZs
qVzqdNdCnnNVVNCGmbncDBlmBlBBnRlZ
VTdCGVvVfffrjpfMQPwm
BPDldDTDPZcggjcccTdNMbbMNSQNqqjtzMbrRb
LvmWsfvssLGnQbQMRQqrSRnz
WpvsVmmpmmfpfJGrHfVCHVvmcDgpDlZphgFgdhclhdgdBlgF
VGwHbNzMMrzHbbHChhqgCqPNghgCqW
ZJVBvBvZWqvRvggP
JBJlBlBZcsBfcJVrHnLwQQGzLQMc
gBWfBPPPfhvVWFfSVfVdjjbvTvwwQppHcHcctTcQTHcZ
DnNnMJMqMJzqchbZtTQQrb
llRmNLDLDGlCsWSFCffWdshd
LpNMZZpqqpfTTwNqLZwGsZqZbdHRHbHGddnCBHRcmzGmmCdG
JFRtRlVStjPlhtjbBzBncmVWdzWBnb
rPhhSlrvQlFFFPgtJlJtFlhlDNTwRMfZTZfDZNrspZLMMsrq
zBLjLFBjLjmHWlzNZlzVCC
dcJrdfddbllJbdMTwDNMZWNVwVDwHT
gRcgJbcbqfgbftdjlqLhFFLPPhGBjm
WfBgBRzQGNNQqmmqZN
nFjCjCpLbtpPJtCDDnCDJpzncrSVbmdVqbhhdqNbSSmrdVSq
CLPJpDLlLlFDpFjjsGRsBGRfWwsHHglz
lSlSlpCRSsWTRLTlWRvlmMrBPjBPjpqrrmqPJMPZ
DDzbhVhQhDGzhQnGGfnHHQGBPZjMqJjBJMBVJmqMdrqqdT
NNGQbFwnHzNzwbQwFnwbfsLCLtsvLsWggFslsTggSc
nvzPvCnlvtwCrZWmWwvvZCQfbbfQfGbqSJJGmqGSFSbJ
LhTBWdsMNNRgNcgDWsDNcVSfQqJGFSFJqSSddQGSJF
HNgchHcWDRNhTNMWwtPrtZZjnHzrnvCz
djhnzRghMMVCBfhh
qjQTrTPQJCDDqBDJ
LQvGrLjTHLjNNPPTpQgtztSmmbFgmgLbFnmL
FRDNFBBRRVFFmbLZHPZBZvvH
QnhgMllglJTdGgJnhLQQJpZpvwZHpwsPTwpbsZHmsH
lnhnQGrMgthMlntlGfQhgWWcRSDcVCrLWzRSrRFDRN
PqrrrRnPBbrVhVqFrFVRPVhZLvNSNvLZcQvtJfRvNScJNJ
dDzWwwCTmmdwdddpDLWQZMSSMfSJtcWJfQSQZN
CCwmTdjsClVjFjnLBl
srjCvjPmQVlPjFPmQmPrdHHZhvHZDqHhDDwHHqfB
pLcnJQNQMZpqZDDZ
WNRbtNJgRPjjQVmz
NJJRmjmJbbJfqSVMNHFCSFzLLlrLLrFHTz
QvnsQGvBwWwQvgRHlGGDFPFCGlrR
QhvwBvBctBccZWZNRNmVfjpmjJjb
RMmGGMLRRCFmRPPfGFpGPFPJWZQWctrtlQvZvltfrQWcWWBq
gggwjjbjwwbZtwZBBcmQQv
SdNbDDVSgPMFmPzdMm
nZhnNZDnZPmZPWbppPpMlvRlzvrtMmRtqRzRfq
HcFwsCQLVQwFwLtLbvtzrlrLtt
GsgCFCgCQHHCVHsFQHcFdDPDbJDZTpZDbWJPNWWZDd
BBrBrGlGpgGjsNhlBlpBwpfSwZJdQwfcZwvSQnnn
LvWvHLmmVJQQHfQH
RPLRMvqFTbRTjGBhjNFsslls
cNZZZmZDcDDJmhzzrrlHtSbvgjSvgfPSWvPfjShv
VBwnndnVCqbqpRRpnspnqRWtGgWSSgvFBSGGSWgtGGSP
LqCMnTLVRwCRCpRLpbHDNzMMNcmmHNHQJQ
MMqDtnVnBlHtZvtB
WLWrWgdWwdrLCTFCwLlbbsJsJQsbQlQzlvrB
jFSvTdjfnfRmVcRR
ZLGqnvnqLzvbGRMfcRpwMpdV
fgfNNfgHHjVmRcVdgM
HsWDCDfCQCZBBZnvWtLq
bTZjqflqZhcrlczGzppGNgjmFNnp
PmmRSWWDMBQVNpWFznGF
SStRBDSCCSSSwPBwBDBwPmZhZlfZhqHTsTfltHHZfsHH
GbNbsSptQGqsdJCzsddcgzzv
DHRRnmWWmZnmRhllnHnnnMLvvLgcTVvjVhCTvgzcJgLj
RnWMlDZRlnHlmHWBFwGQqNGGPNQzPGqFwz
vSGvHpJnBLbGHBNCgfDzzChDgbCfzT
wFRslqmqTRgggQghPmQf
qjRFMjWqNNMMGHTL
fWGcQGGSRFQZhttZJfSSJflDDrwdClljVrNDdrdCFBCr
MTgvLLPPnHzMbDwdlNbMBwMM
mnTvnnPTcNmmJJWN
qqbbQQnbWrqGgnWqvZpVzMCZjCgfjZCSVM
ldcmDPDhmlFBHPDddLBVFDHLppZpjSCjjNfwNMwCpSMwhCMp
FtDdsHPcHmdHVPLtHsdtBHQnsbvnTRRTRsRRqbqvqWnJ
hhtBtPrgbbhhgjZjjCCHHNpNDHpffHWCvr
LGFLVwswsJMSgFwMMpddSvpHCCdDdvCpvm
sGsFsQLsVsLFnnFTJQthjcjQqhRcBZZtRg`.split("\n");

export const scoreData = {
  a: 1,
  b: 2,
  c: 3,
  d: 4,
  e: 5,
  f: 6,
  g: 7,
  h: 8,
  i: 9,
  j: 10,
  k: 11,
  l: 12,
  m: 13,
  n: 14,
  o: 15,
  p: 16,
  q: 17,
  r: 18,
  s: 19,
  t: 20,
  u: 21,
  v: 22,
  w: 23,
  x: 24,
  y: 25,
  z: 26,
  A: 27,
  B: 28,
  C: 29,
  D: 30,
  E: 31,
  F: 32,
  G: 33,
  H: 34,
  I: 35,
  J: 36,
  K: 37,
  L: 38,
  M: 39,
  N: 40,
  O: 41,
  P: 42,
  Q: 43,
  R: 44,
  S: 45,
  T: 46,
  U: 47,
  V: 48,
  W: 49,
  X: 50,
  Y: 51,
  Z: 52,
};
